// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title CarbonCredits
 * @dev An ERC-20 token representing verified carbon credits generated by renewable energy trades.
 * This contract is controlled by the SolarSyncCore for minting.
 */
contract CarbonCredits is ERC20, Ownable {
    // The SolarSyncCore contract address, which is authorized to mint credits
    address public solarSyncCoreAddress;
    // Defines the conversion rate: 1 MWh of clean energy = 1 Carbon Credit (a common standard)
    uint256 private constant KWH_PER_CREDIT = 1000;
    constructor(address _coreAddress)ERC20("SolarSync Carbon Credit", "SSCC")Ownable(msg.sender){
        solarSyncCoreAddress = _coreAddress;
    }
    // Restrict minting ability to only the SolarSyncCore contract
    modifier onlyCoreContract() {
        require(msg.sender == solarSyncCoreAddress, "Caller must be SolarSync Core.");
        _;
    }

    /**
     * @notice Calculates and mints Carbon Credits to a recipient based on delivered renewable energy.
     * @dev This function is called by SolarSyncCore or TradingEngine after a trade is settled.
     * @param recipient The address to receive the credits (usually the producer).
     * @param energyAmountKWh The final, verified amount of renewable energy delivered (in KWh).
     * @return creditsMinted The total number of SSCC tokens minted.
     */

    function calculateAndMintCredits(address recipient, uint256 energyAmountKWh) external onlyCoreContract returns (uint256 creditsMinted) {
        creditsMinted = energyAmountKWh / KWH_PER_CREDIT;
        if (creditsMinted > 0) {
            _mint(recipient, creditsMinted * 10**decimals());
        }
        return creditsMinted;
    }

    /**
     * @notice Allows the owner to update the address of the SolarSyncCore contract.
     * @dev Necessary if the Core contract is upgraded.
     * @param newCoreAddress The address of the new core contract.
     */

    function setCoreContractAddress(address newCoreAddress) external onlyOwner {
        require(newCoreAddress != address(0), "New address cannot be zero.");
        solarSyncCoreAddress = newCoreAddress;
    }
}